apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: ticketing-app
build:
  artifacts:
  - image: kazikdocker/auth
    context: auth
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
